### ISSUE TITLE
[bug] После перезагрузки страницы затирает последнюю точку

### ISSUE THREAD

**Issue by PlayWay** [Le-Roman/game-of-life#12]
1. Строю собственное поле(проставляю точки)
2. Проставил, нажимаю перезагрузку страницы.
![image](https://user-images.githubusercontent.com/46006965/181342340-602a738a-8a3a-46dd-8555-9fa6443f8713.png)

Факт: Последняя проставленная точка затирается
![image](https://user-images.githubusercontent.com/46006965/181342471-c5f8b6c0-279a-4707-9954-fddb9891f282.png)

Ожидание: всё останется как прежде

**Comment by Le-Roman** [comment]
спасибо, исправлено
